# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTesting < Formula
  desc ""
  homepage "https://github.com/PatrickMenoti/homebrew-tools"
  version "1.1.0-beta.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.20/goreleaser-testing_1.1.0-beta.20_Darwin_x86_64.tar.gz"
      sha256 "a51614ef04bac28d34303331d69fa489191af2b1bdcd28b01ba5a2200f23a359"

      def install
        bin.install "goreleaser-testing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.20/goreleaser-testing_1.1.0-beta.20_Darwin_arm64.tar.gz"
      sha256 "33d4ae9a474b8ada066237afaea1867aa6e7eba36caa843049800087d64d1b02"

      def install
        bin.install "goreleaser-testing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.20/goreleaser-testing_1.1.0-beta.20_Linux_x86_64.tar.gz"
      sha256 "76061cf52574341e7e0f54204ff37b899cf80c88db121ccc1960130d851e1cab"

      def install
        bin.install "goreleaser-testing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.20/goreleaser-testing_1.1.0-beta.20_Linux_arm64.tar.gz"
      sha256 "b560f3c38f83c1c7d46b03d9e355d1c3283cd66e7f2c6432460e5608c97d98e3"

      def install
        bin.install "goreleaser-testing"
      end
    end
  end
end
