# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTesting < Formula
  desc ""
  homepage "https://github.com/PatrickMenoti/homebrew-tools"
  version "1.1.0-beta.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.4/goreleaser-testing_1.1.0-beta.4_Darwin_x86_64.tar.gz"
      sha256 "7f4af2509731b12506aebe85f760414599e9be82bfcc2d0981c704f4f802ff32"

      def install
        bin.install "goreleaser-testing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.4/goreleaser-testing_1.1.0-beta.4_Darwin_arm64.tar.gz"
      sha256 "524a4600a1ce58fb2a9cfd79844bbced3a41a7eb5a6337017bc7529a0ad75ed5"

      def install
        bin.install "goreleaser-testing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.4/goreleaser-testing_1.1.0-beta.4_Linux_arm64.tar.gz"
      sha256 "cb21da64b5bf9a9173623773ddc529c37ddf32dba6812efce761bf21150c9145"

      def install
        bin.install "goreleaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PatrickMenoti/goreleaser-testing/releases/download/v1.1.0-beta.4/goreleaser-testing_1.1.0-beta.4_Linux_x86_64.tar.gz"
      sha256 "3add5a5f443fde2d43a9da1a4cb9859e19bb39ffd3e3c50f14c5754f27ffff26"

      def install
        bin.install "goreleaser-testing"
      end
    end
  end
end
